name: altive_lints
repository: https://github.com/altive/altive_lints

packages:
  - packages/**

command:
  version:
    workspaceChangelog: false

scripts:
  custom_lint:
    exec: dart run custom_lint
    description: Run custom_lint.
    packageFilters:
      dependsOn: "custom_lint"

  # Issue on file exclusion feature: https://github.com/dart-lang/dart_style/issues/864
  # NOTE: Using the `exec:` format causes processing to stop
  format:ci:
    run: |
      melos exec -- \
        dart format --set-exit-if-changed lib/
    description: Run dart format for CI.
    packageFilters:
      dirExists: lib
