name: altive_lints
description: >-
  Analyzer-independent lint presets with Altive's recommended rule selection
  and optional Analyzer Plugin integration.
version: 4.0.0
homepage: https://altive.dev
repository: https://github.com/altive/altive_lints
issue_tracker: https://github.com/altive/altive_lints/issues
topics: # up to 5 topics are allowed
  - lint
  - lints
  - linter
  - code-style
  - analyzer

resolution: workspace

environment:
  sdk: ^3.10.0
