name: altive_lints_test
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: ^3.0.0

dev_dependencies:
  altive_lints: 
    path: ../
  clock: ^1.1.1
  custom_lint: ^0.6.5
  flutter:
    sdk: flutter
